Clang warning
../../include/geos/geom/FixedSizeCoordinateSequence.h: In instantiation of ‘std::unique_ptr<geos::geom::CoordinateSequence> geos::geom::FixedSizeCoordinateSequence<N>::clone() const [with long unsigned int N = 1]’
../../include/geos/geom/FixedSizeCoordinateSequence.h:37:45:   required from here
../../include/geos/geom/FixedSizeCoordinateSequence.h:40:33: error: redundant move in return statement [-Werror=redundant-move]
   40 |             return std::move(seq); // move needed for gcc 4.8
      |